import test from 'node:test';import assert from 'node:assert/strict';
import {detectPlatform} from '../site/shared/ads/v1/detect.js';
import {DisabledAdapter,YandexAdapter,VKAdapter} from '../site/shared/ads/v1/adapters.js';
import {AdCoordinator} from '../site/shared/ads/v1/coordinator.js';
import {createAds} from '../site/shared/ads/v1/index.js';
test('MAX launch data arriving after initialization disables capabilities and SDK access',async()=>{let calls=0;const env={location:{},document:{hidden:false,querySelectorAll:()=>[]},dispatchEvent(){},CustomEvent:class{},YaGames:{init:async()=>({adv:{showRewardedVideo(){calls++;}}})}};const manager=await createAds(env);assert(manager.info().capabilities.rewarded);env.WebApp={initData:'max-launch'};assert.equal(manager.info().platform,'max');assert.equal(manager.info().capabilities.rewarded,false);assert.equal(manager.getPlatformSdk(),null);assert.equal((await manager.rewarded()).reason,'max-disabled');assert.equal(calls,0);});
test('MAX remains disabled even with Yandex/VK globals and enabled config',async()=>{const env={location:{search:'?WebAppData=abc&vk_app_id=1&vk_user_id=2'},YaGames:{init(){throw Error('must not call');}}};assert.equal(detectPlatform(env,{platform:'yandex'}),'max');let calls=0;const adapter=new DisabledAdapter('max');adapter.capabilities={interstitial:true,rewarded:true};adapter.show=()=>{calls++;};const c=new AdCoordinator(adapter,{enabled:true,maxEnabled:true});assert.equal((await c.afterRound()).reason,'max-disabled');assert.equal((await c.rewarded()).rewarded,false);assert.equal(calls,0);});
test('Platform detection rejects a loaded compatibility facade and empty MAX bridge',()=>{assert.equal(detectPlatform({location:{},WebApp:{initData:''},YaGames:{__jarvisCompat:true}}),'web');assert.equal(detectPlatform({location:{search:'?vk_app_id=1&vk_user_id=2'}}),'vk');assert.equal(detectPlatform({location:{},YaGames:{init(){}}}),'yandex');});
function yandexHarness(){let callbacks;const env={__JARVIS_YSDK__:{adv:{showRewardedVideo(o){callbacks=o.callbacks;},showFullscreenAdv(o){callbacks=o.callbacks;}}}};const a=new YandexAdapter(env,{});return {a,get callbacks(){return callbacks;}};}
test('Yandex: close without onRewarded never grants, duplicate callbacks grant once',async()=>{const h=yandexHarness();await h.a.init();let grants=0;const c=new AdCoordinator(h.a,{}, {pause(){},resume(){}});let p=c.rewarded({requestId:'a'});await new Promise(r=>setImmediate(r));h.callbacks.onOpen();h.callbacks.onClose(true);assert.equal((await p).rewarded,false);p=c.rewarded({requestId:'b'});await new Promise(r=>setImmediate(r));h.callbacks.onOpen();h.callbacks.onRewarded();h.callbacks.onRewarded();h.callbacks.onClose(true);if((await p).rewarded)grants++;h.callbacks.onRewarded();h.callbacks.onClose(true);assert.equal(grants,1);assert.equal((await c.rewarded({requestId:'b'})).reason,'duplicate');});
test('Busy guard, cooldown, SDK errors and pause/resume balance',async()=>{const h=yandexHarness();await h.a.init();const events=[];let now=0;const c=new AdCoordinator(h.a,{interstitialCooldownMs:100},{pause:()=>events.push('pause'),resume:()=>events.push('resume'),now:()=>now});const p=c.afterRound({roundId:'r1'});await new Promise(r=>setImmediate(r));assert.equal((await c.rewarded()).reason,'busy');h.callbacks.onOpen();h.callbacks.onClose(true);assert((await p).shown);assert.equal((await c.afterRound()).reason,'cooldown');now=101;const p2=c.rewarded();await new Promise(r=>setImmediate(r));h.callbacks.onError({});assert.equal((await p2).rewarded,false);assert.deepEqual(events,['pause','resume','pause','resume']);});
test('Late reward after timeout is ignored; next request cannot overlap an unknown ad',async()=>{const h=yandexHarness();await h.a.init();const c=new AdCoordinator(h.a,{requestTimeoutMs:15});const p=c.rewarded();await new Promise(r=>setImmediate(r));h.callbacks.onOpen();const out=await p;assert.equal(out.reason,'timeout');assert.equal(out.rewarded,false);h.callbacks.onRewarded();h.callbacks.onClose(true);assert.equal((await c.rewarded()).reason,'reload-required');});
test('VK: no fill/cancellation/errors do not grant; confirmed reward does',async()=>{for(const scenario of ['no-fill','cancel','error','reward']){let show=0;const env={vkBridge:{supportsAsync:async()=>true,send:async(method)=>{if(method==='VKWebAppInit')return {};if(method==='VKWebAppCheckNativeAds')return {result:scenario!=='no-fill'};if(method==='VKWebAppShowNativeAds'){show++;if(scenario==='error')throw Error('closed');return {result:scenario==='reward'};}}}};const a=new VKAdapter(env,{});await a.init();const c=new AdCoordinator(a);const r=await c.rewarded();assert.equal(r.rewarded,scenario==='reward');assert.equal(show,scenario==='no-fill'?0:1);}});
test('No advertising call while hidden, disabled or on standalone web',async()=>{let calls=0;const a={platform:'yandex',capabilities:{interstitial:true,rewarded:true},show(){calls++;}};assert.equal((await new AdCoordinator(a,{}, {isHidden:()=>true}).rewarded()).reason,'background');assert.equal((await new AdCoordinator(a,{enabled:false}).afterRound()).reason,'disabled');assert.equal((await new AdCoordinator(new DisabledAdapter()).rewarded()).rewarded,false);assert.equal(calls,0);});
