import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,choose,findPair,exposed,undo,reshuffle,validRun,SHAPES,tick,readProgress,record} from '../site/js/cubes-engine.js';
test('cubes: every generated layout has an exposed-pair solution, even counts and unique positions',()=>{
 for(let shape=0;shape<SHAPES.length;shape++)for(let seed=1;seed<=20;seed++){const s=createRun({shape,seed,level:12,round:seed});assert(validRun(s));const counts=Array(8).fill(0);s.tiles.forEach(t=>counts[t.kind]++);assert(counts.every(n=>n%2===0));assert.equal(new Set(s.tiles.map(t=>t.p.join())).size,s.tiles.length);for(const pair of s.solution){assert(pair.every(id=>exposed(s.tiles).includes(id)));assert.equal(choose(s,pair[0]).type,'select');assert.equal(choose(s,pair[1]).type,'match');}assert(s.won&&s.done);assert.equal(s.pairs,s.tiles.length/2);assert.equal(s.tiles.filter(t=>!t.removed).length,0);}
});
test('cubes: new games never repeat the previous figure',()=>{let previous=-1;const shapes=new Set();for(let round=0;round<100;round++){const s=createRun({round,previous,seed:round*653+99});assert.notEqual(s.shape,previous);shapes.add(s.shape);previous=s.shape;}assert.equal(shapes.size,10);});
test('cubes: same cube toggles off, mismatch changes selection, a pair scores once',()=>{const s=createRun({seed:1}),pair=findPair(s),wrong=s.tiles.find(t=>exposed(s.tiles).includes(t.id)&&t.kind!==s.tiles[pair[0]].kind);assert.equal(choose(s,pair[0]).type,'select');assert.equal(choose(s,pair[0]).type,'deselect');choose(s,wrong.id);assert.equal(choose(s,pair[0]).type,'mismatch');assert.equal(s.mistakes,1);assert.equal(choose(s,pair[1]).type,'match');assert.equal(s.score,100);assert(!choose(s,pair[1]).ok);assert.equal(s.pairs,1);});
test('cubes: buried cubes cannot be selected and undo restores exact previous pair',()=>{const s=createRun({shape:0,seed:9}),buried=s.tiles.find(t=>!exposed(s.tiles).includes(t.id));assert(buried);assert(!choose(s,buried.id).ok);const pair=findPair(s);pair.forEach(id=>choose(s,id));s.seconds=20;assert(undo(s));assert.equal(s.seconds,20);assert.equal(s.score,0);assert.equal(s.pairs,0);assert(pair.every(id=>!s.tiles[id].removed));assert(validRun(s));});
test('cubes: shuffle preserves inventory, clears undo and provides a full solution',()=>{const s=createRun({seed:14,level:9});findPair(s).forEach(id=>choose(s,id));const before=s.tiles.filter(t=>!t.removed).map(t=>t.kind).sort();assert(reshuffle(s));assert.deepEqual(s.tiles.filter(t=>!t.removed).map(t=>t.kind).sort(),before);assert.equal(s.shuffles,2);assert.equal(s.undo.length,0);assert(findPair(s));for(const pair of s.solution)pair.forEach(id=>choose(s,id));assert(s.won);});
test('cubes: exhausted shuffle charges do not allow extra paid shuffles',()=>{const s=createRun({seed:1});s.shuffles=0;assert(findPair(s));const before=JSON.stringify(s);assert.equal(reshuffle(s),false);assert.equal(JSON.stringify(s),before);});
test('cubes: the timer is optional, starts on selection and ends at zero',()=>{const s=createRun({mode:'timed'});tick(s,1000);assert(!s.done);choose(s,findPair(s)[0]);assert(tick(s,1000));assert(s.done&&!s.won);const calm=createRun();choose(calm,findPair(calm)[0]);tick(calm,9999);assert(!calm.done);});
test('cubes: completion is recorded once and legacy level is retained separately',()=>{const p=readProgress(null,{level:7,score:1250});assert.equal(p.run.level,7);assert.equal(p.best,1250);p.run.solution.forEach(pair=>pair.forEach(id=>choose(p.run,id)));const before=p.cleared;record(p,p.run);record(p,p.run);assert.equal(p.cleared,before+1);assert.equal(p.unlocked,8);assert(validRun(JSON.parse(JSON.stringify(p.run))));});
test('cubes: malformed saved games recover safely',()=>{for(const bad of [null,{},createRun()]){if(bad?.tiles)bad.tiles[0].p=[NaN,0,0];assert(!validRun(bad));assert(validRun(readProgress({version:2,run:bad}).run));}});
