import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRun,readProgress,record,choose,findPair} from '../site/js/cubes-engine.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(fileURLToPath(new URL('../site/',import.meta.url))),out=process.env.QA_OUTPUT||'/tmp/cubes-qa';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),checks=[],errors=[];
const check=(name,ok)=>{assert(ok,name);checks.push(name);console.log('PASS:',name);};
async function make(state=createRun({seed:271,level:5}),{fallback=false,offline=false,reducedMotion='reduce'}={}){
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,hasTouch:true,isMobile:true,reducedMotion});page.on('pageerror',e=>errors.push(e.message));const p=readProgress(null);p.seen=true;record(p,state);
 await page.addInitScript(({p,fallback})=>{if(!sessionStorage.getItem('cubes-qa')){localStorage.setItem('jarvis-cubes-dream-v2',JSON.stringify(p));localStorage.setItem('jarvis-sound','false');sessionStorage.setItem('cubes-qa','1');}if(fallback){const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.includes('webgl')?null:original.call(this,type,...args);};}},{p,fallback});
 const external=[];await page.route('**/*',async r=>{const u=new URL(r.request().url());if(u.protocol==='file:')return r.continue();if(u.hostname!=='cubes.test'){external.push(u.href);return r.abort();}try{const f=path.resolve(root,'.'+u.pathname);if(!f.startsWith(root+path.sep))return r.abort();await r.fulfill({body:await readFile(f),contentType:({'.js':'text/javascript','.css':'text/css','.html':'text/html','.ttf':'font/ttf','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream'});}catch{await r.fulfill({status:404,body:'Not found'});}});
 await page.goto(offline?pathToFileURL(path.resolve('../deliverables/Kubomaniya_Mechta_Madzhong.html')).href:'https://cubes.test/play.html?game=cubes');await page.waitForFunction(()=>document.querySelector('#cb-stage')?.dataset.renderer);await page.waitForSelector('[data-cube]:not([hidden])');return{page,external};
}
const read=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('jarvis-cubes-dream-v2'))),ready=p=>p.waitForFunction(()=>document.querySelector('#cb-stage').getAttribute('aria-busy')==='false');
async function visible(p){return p.locator('[data-cube]:not([hidden])').evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return{id:Number(e.dataset.cube),x:r.x+r.width/2,y:r.y+r.height/2};}));}
async function tapId(p,id){for(let i=0;i<40;i++){const a=(await visible(p)).find(t=>t.id===id);if(a){await p.touchscreen.tap(a.x,a.y);return;}await p.locator('#cb-right').tap();if(i%10===9){await p.locator('.cb-canvas').focus();await p.keyboard.press('ArrowUp');await p.keyboard.press('ArrowUp');}await p.waitForTimeout(60);}throw Error('Could not expose cube '+id);}
async function visiblePair(p){for(let n=0;n<24;n++){const s=(await read(p)).run,v=await visible(p);for(const a of v){const b=v.find(b=>b.id!==a.id&&s.tiles.find(t=>t.id===b.id).kind===s.tiles.find(t=>t.id===a.id).kind);if(b)return[a,b];}await p.locator('#cb-right').tap();await p.waitForTimeout(70);}throw Error('No visible pair');}
try{
 const {page}=await make();check('New game route uses true WebGL and the new title',await page.getAttribute('#cb-stage','data-renderer')==='webgl'&&(await page.title()).startsWith('Кубомания: мечта маджонг'));
 const pair=await visiblePair(page);await page.touchscreen.tap(pair[0].x,pair[0].y);check('Real touch selects one cube without removing it',(await read(page)).run.selected===pair[0].id&&(await read(page)).run.pairs===0);await page.touchscreen.tap(pair[1].x,pair[1].y);await ready(page);check('Real touch match removes exactly two cubes and scores once',(await read(page)).run.tiles.filter(t=>t.removed).length===2&&(await read(page)).run.score===100);
 const snapshot=JSON.stringify(await read(page));await page.reload();await page.waitForSelector('[data-cube]:not([hidden])');check('Reload restores the exact committed game',JSON.stringify(await read(page))===snapshot);await page.locator('#cb-undo').tap();check('Undo restores the pair and score',(await read(page)).run.pairs===0&&(await read(page)).run.score===0);
 const cdp=await page.context().newCDPSession(page),bounds=await page.locator('#cb-stage').boundingBox(),from={x:bounds.x+bounds.width*.48,y:bounds.y+bounds.height*.48},to={x:from.x+62,y:from.y+34},before=(await read(page)).run;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[from]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[to]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});let after=(await read(page)).run;check('A drag rotates the figure without choosing or removing a cube',after.rotation[0]!==before.rotation[0]&&after.rotation[1]!==before.rotation[1]&&after.selected===null&&after.pairs===0);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[from]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});check('Touch cancellation never makes a selection',(await read(page)).run.selected===null);
 await page.locator('#cb-hint').tap();check('Hint describes a highlighted pair without spending charges',(await page.locator('#cb-live').innerText()).includes('Золотым')&&(await read(page)).run.shuffles===3);await page.locator('#cb-shuffle').tap();check('Shuffle consumes one charge and keeps every remaining tile',(await read(page)).run.shuffles===2&&(await read(page)).run.tiles.filter(t=>!t.removed).length===36);
 const target=(await visible(page))[0];await page.locator(`[data-cube="${target.id}"]`).focus();await page.keyboard.press('Enter');check('Keyboard focus and Enter select a visible cube',(await read(page)).run.selected===target.id);await page.keyboard.press('Escape');check('Escape clears the selection',(await read(page)).run.selected===null);
 for(const [width,height]of[[320,568],[360,640],[390,844],[430,932],[768,1024],[844,390],[667,375],[1366,768],[1920,1080]]){await page.setViewportSize({width,height});await page.waitForTimeout(130);const metrics=await page.evaluate(()=>{const stage=document.querySelector('#cb-stage'),r=stage.getBoundingClientRect(),root=document.querySelector('#game').getBoundingClientRect();return{fit:document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight&&Math.abs(root.height-innerHeight)<1&&['cb-menu','cb-hint','cb-shuffle','cb-undo','cb-new'].every(id=>{const r=document.getElementById(id).getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.y>=0&&r.bottom<=innerHeight;}),w:r.width,h:r.height,available:Number(stage.dataset.availableHeight),fw:Number(stage.dataset.figureWidth),fh:Number(stage.dataset.figureHeight)};});check(`Full viewport, visible controls and fitted figure at ${width}×${height}`,metrics.fit&&metrics.fw<=metrics.w+.5&&metrics.fh<=metrics.h+.5&&Math.max(metrics.fw/metrics.w,metrics.fh/metrics.available)>.90);if(width===390||width===1366||width===667||width===320)await page.screenshot({path:path.join(out,`cubes-${width}.png`)});}
 await page.setViewportSize({width:390,height:844});const previous=(await read(page)).run;await page.locator('#cb-new').tap();await page.getByRole('button',{name:'Начать',exact:true}).tap();const next=(await read(page)).run;check('New game changes layout, tile shape and background',next.shape!==previous.shape&&next.skin!==previous.skin&&next.world!==previous.world);await page.close();
 const win=createRun({seed:81,level:3});for(const ids of win.solution.slice(0,-1))ids.forEach(id=>choose(win,id));const {page:end}=await make(win);for(const id of findPair(win))await tapId(end,id);await end.waitForSelector('#modal[open]');check('The final pair wins and unlocks the next dream',(await read(end)).run.won&&(await read(end)).unlocked===4);await end.getByRole('button',{name:'Следующая мечта',exact:true}).tap();check('Next dream begins with a new figure and empty score',(await read(end)).run.level===4&&(await read(end)).run.score===0&&(await read(end)).run.shape!==win.shape);await end.close();
 const timed=createRun({mode:'timed',seed:73});timed.started=true;timed.seconds=2;const {page:pause}=await make(timed);await pause.locator('#cb-menu').tap();let seconds=(await read(pause)).run.seconds;await pause.waitForTimeout(900);check('Timer pauses in the menu',(await read(pause)).run.seconds===seconds);await pause.getByRole('button',{name:'Продолжить',exact:true}).tap();await pause.waitForSelector('#modal[open]');check('Timed mode ends the game at zero',(await read(pause)).run.done&&!(await read(pause)).run.won);await pause.close();
 const {page:fallback}=await make(undefined,{fallback:true});check('Canvas fallback renders the same 3D construction without WebGL',await fallback.getAttribute('#cb-stage','data-renderer')==='canvas');const fp=await visiblePair(fallback);for(const p of fp)await fallback.touchscreen.tap(p.x,p.y);await ready(fallback);check('Canvas fallback supports real touch pair matching',(await read(fallback)).run.pairs===1);await fallback.screenshot({path:path.join(out,'cubes-canvas.png')});await fallback.close();
 const {page:offline,external}=await make(createRun({seed:55,shape:2,round:2,level:8}),{offline:true,reducedMotion:'no-preference'});const op=await visiblePair(offline);await offline.touchscreen.tap(op[0].x,op[0].y);await offline.touchscreen.tap(op[1].x,op[1].y);await ready(offline);check('Standalone file plays offline with animations and no external requests',(await read(offline)).run.pairs===1&&external.length===0);await offline.screenshot({path:path.join(out,'cubes-offline.png')});await offline.close();
 const {page:catalog}=await make();await catalog.goto('https://cubes.test/index.html');await catalog.waitForSelector('.game-card');check('Catalog retains 19 games and links to the renamed game',await catalog.locator('.game-card').count()===19&&(await catalog.locator('.game-card[href="play.html?game=cubes"]').innerText()).includes('мечта маджонг'));await catalog.close();check('No unhandled browser exceptions',errors.length===0);await writeFile(path.join(out,'cubes-browser-results.json'),JSON.stringify({passed:checks.length,checks,errors},null,2));
}finally{await browser.close();}
