import {JSDOM} from 'jsdom';import assert from 'node:assert/strict';
const id=process.argv[2];const dom=new JSDOM('<!doctype html><html><body><main id="game"></main><div id="toast"></div><dialog id="modal"></dialog></body></html>',{url:`https://example.test/play.html?game=${id}`,pretendToBeVisual:true});
const w=dom.window;for(const key of ['window','document','location','localStorage','HTMLElement','CustomEvent','Event','MouseEvent','KeyboardEvent'])globalThis[key]=key==='window'?w:w[key];Object.defineProperty(globalThis,'navigator',{value:w.navigator,configurable:true});globalThis.requestAnimationFrame=cb=>setTimeout(()=>cb(performance.now()),0);w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});globalThis.matchMedia=w.matchMedia;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.JarvisAdsReady=Promise.resolve({info:()=>({capabilities:{rewarded:false}}),afterRound:async()=>({shown:false,rewarded:false}),rewarded:async()=>({shown:false,rewarded:false})});
const intervals=[];const origInterval=globalThis.setInterval;globalThis.setInterval=(...args)=>{const t=origInterval(...args);intervals.push(t);return t;};
const modules={sudoku:'puzzles',words:'puzzles',mahjong:'puzzles',chess:'boards',checkers:'boards',corners:'boards',durak:'cards',klondike:'cards',spider:'cards',tricks:'tricks'};
const {start}=await import(`../site/js/${modules[id]}.js`);start(id,document.querySelector('#game'));
const click=s=>{const el=document.querySelector(s);assert(el,`missing ${s}`);el.click();};
assert(document.querySelector('#stage'));assert(document.querySelectorAll('button').length>5);click('#rules');assert(document.querySelector('#modal').open);click('#modal button');
if(id==='sudoku'){const cells=[...document.querySelectorAll('.sudoku-cell')];assert.equal(cells.length,81);const cell=cells.find(b=>!b.classList.contains('given'));cell.click();click('[data-num="4"]');const state=JSON.parse(localStorage.getItem('jarvis-sudoku'));assert.equal(state.board[+cell.dataset.cell],4);}
if(id==='chess'){click('[data-square="e2"]');assert(document.querySelector('[data-square="e4"]').classList.contains('legal'));click('[data-square="e4"]');await new Promise(r=>setTimeout(r,850));assert(localStorage.getItem('jarvis-chess').includes('e4'));}
if(id==='checkers'||id==='corners'){let moved=false;for(let i=0;i<64;i++){document.querySelector('[data-square="'+i+'"]').click();const legal=document.querySelector('.square.legal');if(legal){legal.click();moved=true;break;}}assert(moved);await new Promise(r=>setTimeout(r,700));const s=JSON.parse(localStorage.getItem('jarvis-'+id));assert.equal(s.side,1);assert.equal(s.moves,2);}
if(id==='klondike'||id==='spider'){const before=JSON.parse(localStorage.getItem('jarvis-'+id));click('[data-deal]');const after=JSON.parse(localStorage.getItem('jarvis-'+id));assert.equal(after.stock.length,before.stock.length-(id==='spider'?10:1));}
if(id==='mahjong'){const buttons=[...document.querySelectorAll('[data-tile]')].filter(b=>!b.classList.contains('blocked'));const pair=buttons.flatMap((a,i)=>buttons.slice(i+1).filter(b=>a.textContent===b.textContent).map(b=>[a,b]))[0];assert(pair);pair[0].click();document.querySelector(`[data-tile="${pair[1].dataset.tile}"]`).click();assert.equal(document.querySelectorAll('[data-tile]').length,38);}
if(id==='words'){assert.equal(document.querySelectorAll('[data-letter]').length,36);const s=JSON.parse(localStorage.getItem('jarvis-words'));assert.equal(s.words.join('').length,36);}
if(id==='durak'){await new Promise(r=>setTimeout(r,700));const b=document.querySelector('[data-card]:not(:disabled)');if(b)b.click();else click('#take');await new Promise(r=>setTimeout(r,700));assert(JSON.parse(localStorage.getItem('jarvis-durak')).table.length||document.querySelector('#status').textContent);}
if(id==='tricks'){assert(document.querySelector('.trick-question').textContent.includes('облако'));const buttons=document.querySelectorAll('.trick-object');buttons[1].click();buttons[0].click();await new Promise(r=>setTimeout(r,20));assert(document.querySelector('#modal').open);}
for(const t of intervals)clearInterval(t);dom.window.close();console.log(`${id}: DOM interaction and saved state passed`);process.exit(0);
