import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRun,readProgress,record} from '../site/js/islands-engine.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(fileURLToPath(new URL('../site/',import.meta.url))),out=process.env.QA_OUTPUT||'/tmp/islands-qa';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const errors=[],checks=[],KEY='jarvis-islands-v1';const check=(name,ok)=>{assert(ok,name);checks.push(name);console.log('PASS:',name);};
async function make(state=createRun('journey',1,42),options={}){const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,hasTouch:true,isMobile:true,reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='islands.test')return r.abort();try{const f=path.resolve(root,'.'+u.pathname);if(!f.startsWith(root+path.sep))return r.abort();await r.fulfill({body:await readFile(f),contentType:({'.js':'text/javascript','.css':'text/css','.html':'text/html','.ttf':'font/ttf','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream'});}catch{await r.fulfill({status:404,body:'Not found'});}});const p=readProgress(null);p.seen=true;record(p,state);await page.addInitScript(({p,options})=>{if(!sessionStorage.getItem('islands-qa')){localStorage.setItem('jarvis-islands-v1',JSON.stringify(p));localStorage.setItem('jarvis-sound','false');sessionStorage.setItem('islands-qa','1');}if(options.fallback){const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.includes('webgl')?null:original.call(this,type,...args);};}},{p,options});await page.goto('https://islands.test/play.html?game=islands');await page.waitForSelector('#isl-grid');await page.waitForFunction(()=>document.querySelector('#isl-stage').dataset.renderer);return page;}
const read=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY),ready=page=>page.waitForFunction(()=>document.querySelector('#isl-grid').getAttribute('aria-busy')==='false');
const center=async locator=>{const r=await locator.boundingBox();return {x:r.x+r.width/2,y:r.y+r.height/2};};
try{
 const page=await make();check('True WebGL island with 64 accessible cells',await page.getAttribute('#isl-stage','data-renderer')==='webgl'&&await page.locator('.isl-cell').count()===64);
 await page.locator('[data-cell="56"]').tap();check('Occupied cell rejects the figure without a turn',(await read(page)).journey.turn===0);
 const cdp=await page.context().newCDPSession(page),from=await center(page.locator('[data-slot="0"]')),to=await center(page.locator('[data-cell="62"]'));to.y+=64;
 async function drag(end){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[from]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[to]});await cdp.send('Input.dispatchTouchEvent',{type:end,touchPoints:[]});}
 await drag('touchCancel');check('Cancelled real touch drag preserves the whole hand',(await read(page)).journey.turn===0);
 await drag('touchEnd');await ready(page);let p=await read(page);check('Real touch drag places once and clears the full row',p.journey.turn===1&&p.journey.lines===1&&p.journey.score===130&&p.journey.board.filter(Boolean).length===0);
 const snapshot=JSON.stringify(p);await page.reload();await page.waitForSelector('#isl-grid');check('Reload restores the exact committed board, hand and score',JSON.stringify(await read(page))===snapshot);
 await page.locator('[data-slot="1"]').focus();await page.keyboard.press('Enter');await page.locator('[data-cell="0"]').focus();await page.keyboard.press('Enter');await ready(page);check('Keyboard selects and places a figure',(await read(page)).journey.turn===2);
 await page.locator('#isl-classic').tap();check('Classic mode starts a separate untimed run',(await read(page)).mode==='classic'&&(await read(page)).classic.turn===0);await page.locator('#isl-journey').tap();check('Returning to journey preserves its attempt',(await read(page)).journey.turn===2);
 await page.locator('#isl-hint').tap();check('Hint selects a remaining piece and describes its anchor',(await page.locator('#isl-live').innerText()).includes('строка'));
 await page.locator('#isl-map').tap();check('Map contains 18 levels and locks future islands',await page.locator('[data-level]').count()===18&&await page.locator('[data-level]:disabled').count()===17);await page.getByRole('button',{name:'Закрыть',exact:true}).tap();
 for(const [w,h]of [[320,568],[360,640],[390,844],[768,1024],[844,390],[667,375],[1366,768],[1920,1080]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(80);const fit=await page.evaluate(()=>{const root=document.querySelector('#game').getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight&&root.width===innerWidth&&Math.abs(root.height-innerHeight)<1&&[...document.querySelectorAll('.isl-cell')].every(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('.isl-cell')===e;})&&['isl-menu','isl-hint','isl-wave','isl-rotate'].every(id=>{const r=document.getElementById(id).getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;});});check(`Full viewport and reachable controls at ${w}×${h}`,fit);if(w===667||w===320)await page.screenshot({path:path.join(out,`islands-${w}.png`)});}
 await page.close();
 const energy=createRun('journey',1,23);energy.energy=8;const boosts=await make(energy);await boosts.locator('#isl-rotate').tap();await ready(boosts);check('Rotation charges exactly two energy',(await read(boosts)).journey.energy===6&&(await read(boosts)).journey.tray[0].rotation===1);await boosts.locator('#isl-wave').tap();await boosts.locator('[data-cell="57"]').tap();await ready(boosts);check('Wave removes a 3×3 area without a placement turn',(await read(boosts)).journey.energy===0&&(await read(boosts)).journey.turn===0&&(await read(boosts)).journey.board.filter(Boolean).length===2);await boosts.close();
 const win=createRun('journey',1,7);win.turn=23;win.lines=2;win.score=399;const end=await make(win);await end.locator('[data-cell="61"]').tap();await ready(end);await end.waitForSelector('#modal[open]');check('Last-turn victory opens the next island',(await read(end)).journey.won&&(await read(end)).unlocked===2);await end.getByRole('button',{name:'Следующий остров',exact:true}).tap();check('Next island starts a fresh attempt',(await read(end)).journey.level===2&&(await read(end)).journey.turn===0);await end.close();
 const fallback=await make(undefined,{fallback:true});check('Canvas fallback renders when WebGL is absent',await fallback.getAttribute('#isl-stage','data-renderer')==='canvas');await fallback.locator('[data-cell="61"]').tap();await ready(fallback);check('Canvas fallback keeps the same rules and controls',(await read(fallback)).journey.lines===1);await fallback.screenshot({path:path.join(out,'islands-fallback.png')});await fallback.close();
 const catalog=await make();await catalog.goto('https://islands.test/index.html');await catalog.waitForSelector('.game-card');check('Catalog has 19 games and the new launch link',await catalog.locator('.game-card').count()===19&&await catalog.locator('.game-card[href="play.html?game=islands"]').count()===1);await catalog.locator('#search').fill('Острова');check('Catalog search finds the new game',await catalog.locator('.game-card').count()===1);await catalog.close();
 check('No unhandled browser exceptions',errors.length===0);await writeFile(path.join(out,'islands-browser-results.json'),JSON.stringify({passed:checks.length,checks,errors},null,2));
}finally{await browser.close();}
