import test from 'node:test';
import assert from 'node:assert/strict';
import {newSudoku,sudokuCount,mergeDrop,newCheckers,checkerMoves,applyChecker,newCorners,cornerMoves,cornersWon,newMatch,matchSet,matchHint,matchSwap,newMahjong,freeMahjong,newDurak,durakLegal,durakPlay,durakEndRound,newKlondike,newSpider,moveSolitaire,completeSpider} from '../site/js/engines.js';
test('Sudoku: every generated difficulty has exactly one valid solution',()=>{for(const difficulty of ['easy','normal','hard'])for(let n=0;n<8;n++){const s=newSudoku(difficulty);assert.equal(sudokuCount(s.given),1);assert(s.given.filter(Boolean).length<50);for(let r=0;r<9;r++){assert.equal(new Set(s.solution.slice(r*9,r*9+9)).size,9);assert.equal(new Set(s.solution.filter((_,i)=>i%9===r)).size,9);}s.given.forEach((v,i)=>assert(!v||v===s.solution[i]));}});
test('Merge: gravity, chains, conservation and full-column rejection',()=>{let b=Array(30).fill(0);b[25]=2;b[26]=4;let r=mergeDrop(b,0,2);assert.equal(r.board.reduce((a,b)=>a+b,0),8);assert.equal(Math.max(...r.board),8);assert.equal(r.combo,2);for(let i=0;i<30;i+=5)b[i]=2;assert.equal(mergeDrop(b,0,4),null);assert.equal(b[26],4);});
test('Russian checkers: compulsory backward capture, chain and promotion',()=>{let b=Array(64).fill(0);b[26]=1;b[35]=-1;let moves=checkerMoves(b,1);assert(moves.length&&moves.every(m=>m.captures.length));assert(moves.some(m=>m.to===44));b=Array(64).fill(0);b[40]=1;b[33]=-1;b[19]=-1;moves=checkerMoves(b,1);assert(moves.some(m=>m.to===12&&m.captures.length===2));b=Array(64).fill(0);b[17]=1;b[10]=-1;moves=checkerMoves(b,1);assert(moves.some(m=>m.to===3&&m.piece===2));const m=moves.find(m=>m.to===3);assert.equal(applyChecker(b,m)[3],2);assert.equal(applyChecker(b,m)[10],0);assert.equal(newCheckers().filter(Boolean).length,24);});
test('Corners: jump chains and correct target camp',()=>{const b=Array(64).fill(0);b[56]=1;b[48]=-1;b[32]=-1;assert(cornerMoves(b,1).some(m=>m.to===24&&m.path.length===3));assert.equal(newCorners().filter(v=>v===1).length,9);const won=Array(64).fill(0);for(let r=0;r<3;r++)for(let c=5;c<8;c++)won[r*8+c]=1;assert(cornersWon(won,1));});
test('Match 3: boards start clear, have a legal move, reject non-neighbor swaps',()=>{for(let i=0;i<40;i++){const b=newMatch();assert.equal(matchSet(b).length,0);const hint=matchHint(b);assert(hint);assert(matchSet(matchSwap(b,...hint)).length>=3);assert.equal(matchSwap(b,0,63),null);}});
test('Mahjong: every layout has a complete sequence of free pairs',()=>{for(let n=0;n<12;n++){const tiles=newMahjong();const solve=()=>{if(tiles.every(t=>t.removed))return true;const f=tiles.filter(t=>freeMahjong(tiles,t));for(let i=0;i<f.length;i++)for(let j=i+1;j<f.length;j++)if(f[i].kind===f[j].kind){f[i].removed=f[j].removed=true;if(solve())return true;f[i].removed=f[j].removed=false;}return false;};assert(solve());}});
test('Durak: 100 complete games never duplicate or lose a card',()=>{for(let n=0;n<100;n++){const s=newDurak();for(let step=0;step<5000&&!s.done;step++){const cards=[...s.deck,...s.hands.flat(),...s.discard,...s.table.flatMap(p=>[p.attack,...p.defence?[p.defence]:[]])];assert.equal(cards.length,36);assert.equal(new Set(cards.map(c=>c.id)).size,36);const actor=s.table.some(p=>!p.defence)&&!s.taking?1-s.attacker:s.attacker;const legal=s.hands[actor].filter(c=>durakLegal(s,actor,c)).sort((a,b)=>a.rank+(a.suit===s.trump?20:0)-b.rank-(b.suit===s.trump?20:0));if(legal.length)assert(durakPlay(s,actor,legal[0].id));else if(actor!==s.attacker)s.taking=true;else assert(durakEndRound(s,!!s.taking));}assert(s.done);}});
test('Solitaire rules: deals conserve cards, invalid moves do not mutate state',()=>{for(let i=0;i<20;i++){const k=newKlondike();assert.equal(k.stock.length+k.columns.flat().length,52);assert.equal(k.columns.length,7);assert(k.columns.every(p=>p.at(-1).face));const before=JSON.stringify(k);assert.equal(moveSolitaire(k,{type:'column',col:0,index:0},{type:'column',col:0}),false);assert.equal(JSON.stringify(k),before);const s=newSpider();assert.equal(s.stock.length,50);assert.equal(new Set([...s.stock,...s.columns.flat()].map(c=>c.id)).size,104);}
 const s=newSpider();s.columns[0]=Array.from({length:13},(_,i)=>({id:200+i,rank:13-i,suit:0,face:true}));completeSpider(s);assert.equal(s.completed.length,1);assert.equal(s.columns[0].length,0);
});
